language: php

php:
    - 5.5
    - 5.6
    - 7.0

before_script:
    - echo "extension=zmq.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer update
    - cp config/environment.yml.dist config/environment.yml
    - cp config/environment_test.yml.dist config/environment_test.yml
    - php bin/console --env=test orm:schema-tool:create

script:
    - ./vendor/bin/phpcs --standard=phpcs.xml src
    - phpunit -c .
