language: php

php:
    - 5.5
    - 5.6

before_script:
    - echo "extension=zmq.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer update
    - cp /home/travis/build/alcalyn/eole-api/config/environment.yml.dist /home/travis/build/alcalyn/eole-api/config/environment.yml
    - cp /home/travis/build/alcalyn/eole-api/config/environment_test.yml.dist /home/travis/build/alcalyn/eole-api/config/environment_test.yml
    - php /home/travis/build/alcalyn/eole-api/bin/console-test orm:schema-tool:create
